import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

/**
 * Sidebars Configuration.
 *
 * @since 0.11.0
 */
const config: SidebarsConfig = {
  docs: [{
    type: 'autogenerated',
    dirName: '.',
  }],
};

export default config;
